#ifndef IMAGENS_H
#define IMAGENS_H


/* XPM */
static const char *img_torre[] = {
/* columns rows colors chars-per-pixel */
"50 50 2 1 ",
"  c None",
". c black",
/* pixels */
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"           .....     ..........     .....         ",
"           .    .    .        .    .    .         ",
"           .    .    .        .    .    .         ",
"           .     .....        .....     .         ",
"           .                            .         ",
"           .                            .         ",
"           .                            .         ",
"           ..............................         ",
"            .                         .           ",
"             .                       .            ",
"              .                     .             ",
"               .....................              ",
"               .                   .              ",
"               .                   .              ",
"               .                   .              ",
"               .                   .              ",
"               .                   .              ",
"               .                   .              ",
"               .                   .              ",
"               .                   .              ",
"               .                   .              ",
"               .                   .              ",
"               .                   .              ",
"               .                   .              ",
"               .                   .              ",
"               .                   .              ",
"               .                   .              ",
"               .                   .              ",
"               .....................              ",
"              .                     .             ",
"              .                      .            ",
"             .                       .            ",
"             .                        .           ",
"           ..............................         ",
"           .                            .         ",
"           .                            .         ",
"           .                            .         ",
"        ....................................      ",
"        .                                  .      ",
"        .                                  .      ",
"        .                                  .      ",
"        ....................................      ",
"                                                  "
};

static const char *img_rainha[] = {
/* columns rows colors chars-per-pixel */
"50 50 2 1 ",
"  c None",
". c black",
/* pixels */
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                       ....                       ",
"              ..       .  .      ...              ",
"             .  .      .  .      .  ..            ",
"             .  .      .  .     .    .            ",
"             .  .       ..       .   .            ",
"    ...       ..        ..        ...     ....    ",
"    .  ..     ..        ..        ..      .   .   ",
"   .    .     ..        ..        ..     .    .   ",
"    .  ..     . .       ..        ..      .  .    ",
"    .  .      . .       . .      . .       ..     ",
"     ...      .  .      . .      . .      ..      ",
"      . .     .  .      . .     .  .      ..      ",
"      . .     .  .     .  .     .  .     . .      ",
"      .  .    .   .    .   .    .  .     . .      ",
"      .  .    .   .    .   .   .   .    .  .      ",
"      .   .   .    .   .   .   .   .    .  .      ",
"       .  .   .    .  .    .   .   .   .   .      ",
"       .  .   .     . .     . .    .   .   .      ",
"       .   .  .     . .     . .    .  .   ..      ",
"       .   .  .     . .     ..     .  .   .       ",
"       .    . .      .      ..     . .    .       ",
"        .   ...      . .... ..     . .    .       ",
"        .    ...........  ............    .       ",
"        ........             ..   ......  .       ",
"        ...                             ...       ",
"        .                                .        ",
"        .                                .        ",
"         ..      ................      ...        ",
"          ........              ........          ",
"           ..                        ..           ",
"           .                          .           ",
"            .     ..............     .            ",
"            .. ...              ......            ",
"            ....                  ....            ",
"            ..                      ..            ",
"            .    ................    .            ",
"            . .....           ...... .            ",
"            .....                .....            ",
"            .....                .....            ",
"              ......................              ",
"                  ..............                  ",
"                                                  ",
"                                                  "
};

static const char *img_cavalo[] = {
/* columns rows colors chars-per-pixel */
"50 50 2 1 ",
"  c None",
". c black",
/* pixels */
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                     .                            ",
"            ..      ..                            ",
"            . ..    . .                           ",
"            .   ....  .                           ",
"            .   ..     .                          ",
"            .  .       .......                    ",
"            ...               ...                 ",
"            .                    .                ",
"           .                      ..              ",
"         ..                         .             ",
"        .                            .            ",
"        .                            .            ",
"        .  ..                         .           ",
"        .  ..                         .           ",
"        .                 .            .          ",
"        .                 .            .          ",
"        .                 .             .         ",
"       .                 .              .         ",
"       .                 .               .        ",
"      .                 .                .        ",
"     .                  .                 .       ",
"    .                  .                  .       ",
"    .               ....                  .       ",
"   .              ..   .                  .       ",
"   .            ..     .                  .       ",
"   .  .       ..       .                  .       ",
"   . ...     .        .                    .      ",
"   .  .      .        .                    .      ",
"   .        .        .                     .      ",
"   .        .       .                      .      ",
"    ..     .        .                      .      ",
"      ..   .       .                       .      ",
"        ...       .                        .      ",
"                  .                        .      ",
"                 .                          .     ",
"                .                           .     ",
"               .                            .     ",
"              .                             .     ",
"              .                             .     ",
"              .                              .    ",
"              .                              .    ",
"              ................................    ",
"                                                  ",
"                                                  "
};


static const char *img_bispo[] = {
/* columns rows colors chars-per-pixel */
"50 50 2 1 ",
"  c None",
". c black",
/* pixels */
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                        ..                        ",
"                     ... ..                       ",
"                    ..     .                      ",
"                    .     ..                      ",
"                    ..    .                       ",
"                    ..    .                       ",
"                     ......                       ",
"                     ... ..                       ",
"                    ..     ...                    ",
"                  ..        ...                   ",
"                ...            .                  ",
"                ...            .                  ",
"               ...              ..                ",
"              .         .        .                ",
"              .         .         ..              ",
"             .      ........      ..              ",
"             .          .           .             ",
"             .          .           .             ",
"             .          .           .             ",
"             .          .           .             ",
"             .                      .             ",
"             .                      .             ",
"             ..                   ..              ",
"             ..                   ..              ",
"              ..   ...........  ..                ",
"                ....          ...                 ",
"                ..              .                 ",
"               .                .                 ",
"               .     ......     ..                ",
"               .     ......     ..                ",
"               .......     ..... .                ",
"              ....              ..                ",
"               .                 .                ",
"               .....          ...                 ",
"                   ...........                    ",
"                   ...........                    ",
"                      .....                       ",
"         ......      .    ..      .....           ",
"        ..    .......      .......     ...        ",
"      ..                                ...       ",
"    ...                 ..                 .      ",
"    ...                 ..                 .      ",
"   ...    .............. ..............     ..    ",
"   ...  ..                            ....  .     ",
"    ....                                ....      ",
"                                                  "
};



static const char *ico_xadrez[] = {
/* columns rows colors chars-per-pixel */
"16 16 4 1 ",
"  c #FF7F27",
". c #6B5B95",
"X c #A8A7A2",
"o c white",
/* pixels */
"                ",
"X..............X",
"X.XXooXXooXXoo.X",
"X.XXooXXooXXoo.X",
"X.ooXXooXXooXX.X",
"X.ooXXooXXooXX.X",
"X.XXooXXooXXoo.X",
"X.XXooXXooXXoo.X",
"X.ooXXooXXooXX.X",
"X.ooXXooXXooXX.X",
"X.XXooXXooXXoo.X",
"X.XXooXXooXXoo.X",
"X.ooXXooXXooXX.X",
"X.ooXXooXXooXX.X",
"X..............X",
"XXXXXXXXXXXXXXXX"
};

static const char *ico_nova_peca[] = {
/* columns rows colors chars-per-pixel */
"16 16 136 2 ",
"   c None",
".  c #0049AE",
"X  c #0150B4",
"o  c #0C5FBD",
"O  c #105DB9",
"+  c #125EB9",
"@  c #1465BF",
"#  c #1E6ABF",
"$  c #3974BF",
"%  c #1566C0",
"&  c #1975CC",
"*  c #1875CD",
"=  c #1D78D0",
"-  c #257ECC",
";  c #3773C0",
":  c #397FCB",
">  c #0085D9",
",  c #0B84D9",
"<  c #0F88DA",
"1  c #0D8ADC",
"2  c #0C8BDC",
"3  c #0D8CDC",
"4  c #1C82D5",
"5  c #1D83D5",
"6  c #1F82D5",
"7  c #1F83D5",
"8  c #1D88D6",
"9  c #138BDB",
"0  c #1B8ADB",
"q  c #1C89D8",
"w  c #1E8CD9",
"e  c #1D8DDB",
"r  c #1792DD",
"t  c #1793DD",
"y  c #1793DE",
"u  c #1494DE",
"i  c #1594DE",
"p  c #1596DF",
"a  c #2980CD",
"s  c #2D84D0",
"d  c #3185D0",
"f  c #3489D2",
"g  c #3B8AD2",
"h  c #2293DB",
"j  c #369BD6",
"k  c #1B92E0",
"l  c #1E98E1",
"z  c #1F9CE2",
"x  c #209AE1",
"c  c #209DE1",
"v  c #219DE1",
"b  c #219EE1",
"n  c #219DE2",
"m  c #219EE2",
"M  c #2B99E1",
"N  c #1DA0E7",
"B  c #20A0E3",
"V  c #24A2E6",
"C  c #22A4E4",
"Z  c #2DA4E4",
"A  c #2EA7E4",
"S  c #24A3E8",
"D  c #2CA9EA",
"F  c #36A9E5",
"G  c #33AEEA",
"H  c #4482C9",
"J  c #4582C9",
"K  c #4594D3",
"L  c #4193D8",
"P  c #44B1E9",
"I  c #58BAE7",
"U  c #6EBBE5",
"Y  c #6FBCE6",
"T  c #76B5E0",
"R  c #7AB5E0",
"E  c #7BB7E3",
"W  c #7CBAE4",
"Q  c #8FC5E6",
"!  c #95C1E7",
"~  c #96D2ED",
"^  c #B3D2E9",
"/  c #A6DAF2",
"(  c #A4DCF3",
")  c #A1E2F7",
"_  c #A6E2F6",
"`  c #A7E2F7",
"'  c #A9E3F7",
"]  c #ADE4F6",
"[  c #AEE4F6",
"{  c #A2E3F8",
"}  c #A3E3F8",
"|  c #A4E3F8",
" . c #A3E4F8",
".. c #A7E4F8",
"X. c #A9E6F8",
"o. c #AAE6F9",
"O. c #B1E4F6",
"+. c #B7E7F7",
"@. c #B8E6F5",
"#. c #BAE7F6",
"$. c #BAE7F7",
"%. c #B8E8F7",
"&. c #BFEAF7",
"*. c #BEEEFB",
"=. c #D5DEED",
"-. c #C3EAF8",
";. c #CBECFA",
":. c #CCEDFA",
">. c #D2E8F3",
",. c #D7EDF8",
"<. c #C6F1FE",
"1. c #D6F4FD",
"2. c #EBF6F9",
"3. c #EBF5FA",
"4. c #EEF7FC",
"5. c #E0F9FF",
"6. c LightCyan",
"7. c #E2FFFF",
"8. c #E4FFFF",
"9. c #E6FFFF",
"0. c #E9FFFF",
"q. c #EEFEFF",
"w. c #F3F6FB",
"e. c #F6F4F8",
"r. c #F1FFFF",
"t. c #F2FFFF",
"y. c #FAFAFB",
"u. c snow",
"i. c #FEFBFB",
"p. c #FBFAFC",
"a. c #FBFDFD",
"s. c #FBFFFF",
"d. c #FEFCFC",
"f. c #FFFDFD",
"g. c #FFFFFE",
"h. c white",
/* pixels */
"          + ; H H $ @           ",
"      . T <.t.h.h.6.-.R .       ",
"    o %.q.5.;.-.-.;.1.6.-.o     ",
"  X @.0.@.[ ' ' _ ' [ +.t.@.X   ",
"  E 6._ ) { { | ....X._ X.8.W   ",
"% O.Y ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ Y Q @ ",
": ( h.U i.I w.y.I h.I i.I h.I # ",
"g / h.h.p.j 4.>.K y.=.h.=.e.I - ",
"L Z h.,.h.d 3.L d ! h.^ h.=.j f ",
"s F h.> h.A 3.h.> > h.> h.> A a ",
"* P l l l l x l l l l l l l G & ",
"  h V z b l b b z z z z z D M   ",
"  = x B N p C b b b b b C S =   ",
"    5 r k i t t r y i i N 5     ",
"      5 9 < 3 1 1 1 , k 5       ",
"          8 q 0 0 w w           "
};

static const char *ico_dama[] = {
/* columns rows colors chars-per-pixel */
"16 16 5 1 ",
"  c #7F330A",
". c #FF7F27",
"X c #E6A35C",
"o c #6B5B95",
"O c #A8A7A2",
/* pixels */
"................",
"OooooooooooooooO",
"Oo  XX  XX  XXoO",
"Oo  XX  XX  XXoO",
"OoXX  XX  XX  oO",
"OoXX  XX  XX  oO",
"Oo  XX  XX  XXoO",
"Oo  XX  XX  XXoO",
"OoXX  XX  XX  oO",
"OoXX  XX  XX  oO",
"Oo  XX  XX  XXoO",
"Oo  XX  XX  XXoO",
"OoXX  XX  XX  oO",
"OoXX  XX  XX  oO",
"OooooooooooooooO",
"OOOOOOOOOOOOOOOO"
};

static const char *ico_abrir[] = {
/* columns rows colors chars-per-pixel */
"16 16 182 2 ",
"   c None",
".  c #8B2801",
"X  c #8B2A09",
"o  c #A03A06",
"O  c #A23C05",
"+  c #A63F06",
"@  c #AC4206",
"#  c #B75014",
"$  c #BB5214",
"%  c #A34724",
"&  c #A84C25",
"*  c #A14A28",
"=  c #B35425",
"-  c #BC5A29",
";  c #DB5F0B",
":  c #DB5F0D",
">  c #C25614",
",  c #C15910",
"<  c #C45B10",
"1  c #C45C10",
"2  c #C65E12",
"3  c #C85E10",
"4  c #CA5F1B",
"5  c #D95E10",
"6  c #C46014",
"7  c #C66316",
"8  c #C66418",
"9  c #C6651A",
"0  c #C6671B",
"q  c #C6691E",
"w  c #D26214",
"e  c #D76416",
"r  c #D96010",
"t  c #D96716",
"y  c #C25D28",
"u  c #C96D20",
"i  c #CD602B",
"p  c #D06A2B",
"a  c #D16A2C",
"s  c #D06B2D",
"d  c #D16B2D",
"f  c #D16C2D",
"g  c #D26C2D",
"h  c #D36D2E",
"j  c #D56E2E",
"k  c #C27033",
"l  c #F98D1D",
"z  c #F88E1E",
"x  c #FF921F",
"c  c #F89323",
"v  c #FB9222",
"b  c #FB9623",
"n  c #FF9520",
"m  c #FF9720",
"M  c #F99425",
"N  c #FF9A20",
"B  c #FF9A21",
"V  c #FF9F22",
"C  c #FF9924",
"Z  c #FF9B25",
"A  c #FF9E25",
"S  c #F89628",
"D  c #F99829",
"F  c #FA9829",
"G  c #FA992B",
"H  c #F9992C",
"J  c #FA9B2D",
"K  c #FA9C2D",
"L  c #FA9D2D",
"P  c #F99C2F",
"I  c #FA9F31",
"U  c #FFA129",
"Y  c #FFA62E",
"T  c #FAA331",
"R  c #F9A033",
"E  c #FAA032",
"W  c #FAA133",
"Q  c #FAA235",
"!  c #F9A337",
"~  c #FBA236",
"^  c #FAA436",
"/  c #FAA437",
"(  c #FBA636",
")  c #FFA932",
"_  c #FFAE36",
"`  c #FAA639",
"'  c #FAA739",
"]  c #FAA73A",
"[  c #FBA73D",
"{  c #FCAA3A",
"}  c #FBA93C",
"|  c #FCAA3E",
" . c #FCAB3F",
".. c #FCAE3E",
"X. c #FFB13B",
"o. c #FFB43F",
"O. c #D98148",
"+. c #FCAC40",
"@. c #FCAE41",
"#. c #FCAF43",
"$. c #FDAD4D",
"%. c #FEB140",
"&. c #FCB142",
"*. c #FCB044",
"=. c #FCB145",
"-. c #FCB346",
";. c #FEB745",
":. c #FDB546",
">. c #FFB843",
",. c #FFBC41",
"<. c #FCB348",
"1. c #FDB54A",
"2. c #FCB64C",
"3. c #FDB94A",
"4. c #FDB84D",
"5. c #FEBB4C",
"6. c #FDBA4F",
"7. c #FDBD4E",
"8. c #FEBF4E",
"9. c #FDBD50",
"0. c #FDBC5F",
"q. c #FDBF6A",
"w. c #FDC253",
"e. c #FDC062",
"r. c #FDC467",
"t. c #FEC961",
"y. c #FDC669",
"u. c #FFC06F",
"i. c #FDC272",
"p. c #FFC476",
"a. c #FFC576",
"s. c #FDC971",
"d. c #FEC57C",
"f. c #FDC67E",
"g. c #FFCB7B",
"h. c #FFC87E",
"j. c #FFD379",
"k. c #FFD77E",
"l. c #FFCB80",
"z. c #FFCD83",
"x. c #FED382",
"c. c #FFD187",
"v. c #FFDD80",
"b. c #FFDF80",
"n. c #FFDB84",
"m. c #FFD48B",
"M. c #FFD68D",
"N. c #FFD890",
"B. c #FEDA91",
"V. c #FED993",
"C. c #FEDA93",
"Z. c #FFDF93",
"A. c #FEDC94",
"S. c #FFDE95",
"D. c #FEDF95",
"F. c #FFE197",
"G. c #FFE298",
"H. c #FFE599",
"J. c #FFE99D",
"K. c #F8DEA8",
"L. c #FFE0A5",
"P. c #FFE1A7",
"I. c #FFE2A7",
"U. c #FFEFA6",
"Y. c #FFE4A9",
"T. c #FFE5A9",
"R. c #FFE6AC",
"E. c #FFECAA",
"W. c #FFE9AF",
"Q. c #FFF1A8",
"!. c #FCE5B2",
"~. c #FAE5B6",
"^. c #FBE8B3",
"/. c #FFEBB0",
"(. c #FFEDB2",
"). c #FFEFB4",
"_. c #FFF9B1",
"`. c #FFF5BD",
"'. c #FFF4BE",
"]. c #FFFBBF",
"[. c #FFF8C0",
"{. c #FFFFD4",
/* pixels */
"                                ",
"  ; r 5 r                       ",
"e ~.^.!.P.e                     ",
"j {.Q.U._.w                     ",
"y ].H.G.J.O.i f f f p p f f f   ",
"y [.F.D.Z.)./././.T.T.P.P.P.Y.9 ",
"y '.F.A.N.N.N.M.m.c.z.h.a.a.h.> ",
"- '.Z.N.x.s.y.y.0.q.u.i.d.d.h.$ ",
"= E.t.w.7.3.:.&.{ { ( T ^ $.u.# ",
"= k.w.7.6.2.-.@. .} ^ R L b Z @ ",
"& n.7.2.1.-.@. .} ^ R L G G C @ ",
"& k.:.<.#. .} ' R R G D v v x + ",
"% k.o.o. .' ! R L D S v z x x O ",
"* k.,.>.>.X._ ) Y U U C C x U O ",
"X k q q 0 8 8 7 6 1 1 1 3 6 $ . ",
"                                "
};

static const char *ico_salvar[] = {
/* columns rows colors chars-per-pixel */
"16 16 184 2 ",
"   c None",
".  c #625C65",
"X  c #645F68",
"o  c #77717A",
"O  c #76727B",
"+  c #0465B9",
"@  c #0465BA",
"#  c #0A69BC",
"$  c #156AB9",
"%  c #136BBD",
"&  c #5E7795",
"*  c #5C7997",
"=  c #5D7997",
"-  c #5E7A9A",
";  c #7C7982",
":  c #7C7983",
">  c #607B9A",
",  c #1B76C1",
"<  c #1975C2",
"1  c #1D76C0",
"2  c #1F79C3",
"3  c #257BC7",
"4  c #857F89",
"5  c #6F889F",
"6  c #788EA2",
"7  c #2B80C9",
"8  c #3185CC",
"9  c #348BD0",
"0  c #3A90D2",
"q  c #3D93D5",
"w  c #3E96D7",
"e  c #209EE5",
"r  c #14A7EA",
"t  c #2BA6E7",
"y  c #37ACE8",
"u  c #3CAEE8",
"i  c #36B7EF",
"p  c #5C97C1",
"a  c #5195CD",
"s  c #449BD9",
"d  c #5396D0",
"f  c #589BD4",
"g  c #5B9ED6",
"h  c #649AC1",
"j  c #48A1DC",
"k  c #4FAFDE",
"l  c #5CA3D8",
"z  c #5EA4D9",
"x  c #66A9DC",
"c  c #67ABDD",
"v  c #69ACDE",
"b  c #42A4E2",
"n  c #4CA7E0",
"m  c #45AAE4",
"M  c #47AFE5",
"N  c #51ACE3",
"B  c #40B3EA",
"V  c #47B4EA",
"C  c #49B7ED",
"Z  c #5BB2E7",
"A  c #52B5EB",
"S  c #50B9EB",
"D  c #54BDEE",
"F  c #5ABDED",
"G  c #73B9E5",
"H  c #75BCE9",
"J  c #5DC8FB",
"K  c #56D0FF",
"L  c #5DD2FF",
"P  c #79C0EA",
"I  c #7EC4EC",
"U  c #63C2F0",
"Y  c #6DC6F0",
"T  c #6BCAF7",
"R  c #63CBFB",
"E  c #62CCFB",
"W  c #69CFFD",
"Q  c #6ACFFD",
"!  c #75CCF3",
"~  c #7DCAF4",
"^  c #65D1FB",
"/  c #6ED2FF",
"(  c #7ED0F3",
")  c #78DAFF",
"_  c #73E8FF",
"`  c #85818A",
"'  c #8B8892",
"]  c #8C8994",
"[  c #89919E",
"{  c #94919A",
"}  c #95939E",
"|  c #9296A2",
" . c #9E99A4",
".. c #9E9BA7",
"X. c #959CA8",
"o. c #9F9DA9",
"O. c #86A3BA",
"+. c #9EABB5",
"@. c #A2A0AD",
"#. c #87A8C0",
"$. c #88A8C0",
"%. c #A2B4C2",
"&. c #A9BCC6",
"*. c #A7BAC8",
"=. c #B2BDC7",
"-. c #AFC0CE",
";. c #B8C0CA",
":. c #BFC6CD",
">. c #BFC6CE",
",. c #AFC4D3",
"<. c #B9C7D1",
"1. c #8AC4E6",
"2. c #81C6EC",
"3. c #88C7E8",
"4. c #92CFED",
"5. c #94CFEF",
"6. c #92D0EE",
"7. c #93D0EE",
"8. c #92D1EE",
"9. c #82CAF0",
"0. c #84D4F5",
"q. c #8BD5F6",
"w. c #89D8F5",
"e. c #81D2F9",
"r. c #8EDAF9",
"t. c #88DEFF",
"y. c #96D3F2",
"u. c #9BD6F6",
"i. c #9BD7F7",
"p. c #93D9F6",
"a. c #97DAF6",
"s. c #9EDDF8",
"d. c #90E2FF",
"f. c #9BE0F8",
"g. c #C0C6CD",
"h. c #C9C5C8",
"j. c #D4CECF",
"k. c #CAD0D6",
"l. c #D0D3D6",
"z. c #D4D7DC",
"x. c #D9D9DB",
"c. c #DDDBDC",
"v. c #DDDDDD",
"b. c #DEDDDC",
"n. c #DCDDDF",
"m. c #DCDEDF",
"M. c #DDDEDF",
"N. c #EBDED7",
"B. c #DDE0DF",
"V. c #DEE0DF",
"C. c #E9E0DD",
"Z. c #F5E4D8",
"A. c #F6E5DB",
"S. c #F8E7DA",
"D. c #F8E7DB",
"F. c #F8E8DB",
"G. c #F9E8DB",
"H. c #DDDFE0",
"J. c #DDDFE1",
"K. c #DEDFE0",
"L. c #DFE0E1",
"P. c #D5F4FE",
"I. c #E2E4E5",
"U. c #E3E5E7",
"Y. c #E4E5E6",
"T. c #EFE7E3",
"R. c #EAE8E7",
"E. c #E6E9EB",
"W. c #E9E8EC",
"Q. c #E8EBEC",
"!. c #E9EBEC",
"~. c gray93",
"^. c #F6EEEA",
"/. c #EFF0EF",
"(. c #FFF6E9",
"). c #F9F3EF",
"_. c #FFF8E9",
"`. c #FFF6F1",
"'. c #FFFFF5",
"]. c #FFFDF6",
"[. c #FFFEF6",
"{. c #FFFFFB",
"}. c #FEFEFF",
"|. c white",
/* pixels */
"2.9.~ 3.7.7.7.7.7.y.i.i.1.A     ",
"I P.d.z.].].].].}.m.*.m.I.t.m   ",
"P f.^ ,.^.!.!.E.{.6 k X.<.) w.b ",
"H s.W -.T.Y.Y.I.`.O._ +.;./ r.Z ",
"G a.E *.C.L.v.H.).5 M [ =.W 0.N ",
"x p.J %.N.v.v.c.R.*.| %.&.R ( n ",
"x q.K $.h.:.:.g.:.k.l.j.$.L ! j ",
"v e.p > = = = = = = = & - h T s ",
"l Y z.}.}.}.}.}.}.}.}.}.}.z.D w ",
"l U z.!.o. .{ ' ` ; o . W.z.C 0 ",
"g F z.}.}.}.}.}.}.}.}.}.}.z.B 9 ",
"f S z.!.o. .{ ' 4 ; o . W.z.y 8 ",
"d V z./.m.L.H.V.H.V.V.x.~.z.t 7 ",
"a u z.W.@.o.} ] ` ; O X W.z.e 3 ",
"q i g.(.A.G.G.G.F.A.F.Z._.g.r % ",
", < % + + + + + + + + + + # $ 7 "
};

static const char *ico_sair[] = {
/* columns rows colors chars-per-pixel */
"16 16 170 2 ",
"   c None",
".  c #00030D",
"X  c #0E0D18",
"o  c #191012",
"O  c #1A1113",
"+  c #1B1114",
"@  c #12121D",
"#  c #14101C",
"$  c #2F0000",
"%  c #001A25",
"&  c #0B1822",
"*  c #1B1F30",
"=  c #201F23",
"-  c #445A6E",
";  c #B9281F",
":  c #C60D0D",
">  c #D91416",
",  c red",
"<  c #F3140E",
"1  c #E82A1D",
"2  c #F42E15",
"3  c #F9251B",
"4  c #F23C1F",
"5  c #E82C23",
"6  c #EB2E22",
"7  c #EF3024",
"8  c #EF3A27",
"9  c #E7372E",
"0  c #F43721",
"q  c #FF3220",
"w  c #F23823",
"e  c #F43A22",
"r  c #FF3C21",
"t  c #FF3F2B",
"y  c #FF3E2F",
"u  c #F0403B",
"i  c #F35C42",
"p  c #F15F49",
"a  c #EF5F58",
"s  c #F76545",
"d  c #F6674A",
"f  c #F6694E",
"g  c #EF695C",
"h  c #FF7F5E",
"j  c #F16D63",
"k  c #F16F65",
"l  c #F07066",
"z  c #F47766",
"x  c #FF8A63",
"c  c #094A80",
"v  c #094F86",
"b  c #084F8F",
"n  c #0B538A",
"m  c #0E538E",
"M  c #07509E",
"N  c #2A5CA4",
"B  c #066FAA",
"V  c #1D64AC",
"C  c #1B60B0",
"Z  c #1874BC",
"A  c #2068A4",
"S  c #2876AA",
"D  c #2F7BAF",
"F  c #3A79A8",
"G  c #2169B0",
"H  c #256DB3",
"J  c #2972B7",
"K  c #2C77BB",
"L  c #2F7CBF",
"P  c #455689",
"I  c #176EC1",
"U  c #1378CD",
"Y  c #B46786",
"T  c #3784B6",
"R  c #3F80B2",
"E  c #63869E",
"W  c #4989B9",
"Q  c #7CA7BB",
"!  c #1C89CB",
"~  c #1B89CC",
"^  c #1B8ACD",
"/  c #1C89CC",
"(  c #1C8ACD",
")  c #1D8ACD",
"_  c #1D8ACE",
"`  c #1D8BCF",
"'  c #1F8CCE",
"]  c #1F8CCF",
"[  c #1F8DCF",
"{  c #1B95D6",
"}  c #1C94D6",
"|  c #1D94D6",
" . c #1B94D8",
".. c #1F9CDF",
"X. c #228ECF",
"o. c #3483C3",
"O. c #3D8EC2",
"+. c #3586C8",
"@. c #3E95CC",
"#. c #228FD0",
"$. c #238FD0",
"%. c #2791D2",
"&. c #2792D2",
"*. c #2493D6",
"=. c #2096D7",
"-. c #2992D3",
";. c #2B93D4",
":. c #2E98D6",
">. c #2092D8",
",. c #2599D8",
"<. c #2299DD",
"1. c #2D9CDA",
"2. c #369AD5",
"3. c #3D9AD2",
"4. c #319FDB",
"5. c #198FE3",
"6. c #209CE3",
"7. c #219AE4",
"8. c #229EE6",
"9. c #2AA8F5",
"0. c #30A9F5",
"q. c #4493CF",
"w. c #4598CD",
"e. c #5799C4",
"r. c #4A99D3",
"t. c #4F9FD7",
"y. c #4BA5DA",
"u. c #49A7DB",
"i. c #4BA7DD",
"p. c #55A7DC",
"a. c #56AEDE",
"s. c #58AFDF",
"d. c #48A2E4",
"f. c #4EAAE1",
"g. c #4BAEE1",
"h. c #4EADE6",
"j. c #4BA8EA",
"k. c #5DB0E0",
"l. c #5EB2E0",
"z. c #5CB5E7",
"x. c #4DBAF0",
"c. c #60AFE2",
"v. c #61B2E2",
"b. c #62B4E2",
"n. c #68B7E2",
"m. c #69B8E3",
"M. c #6AB8E4",
"N. c #73BFE6",
"B. c #73BFE7",
"V. c #74C0E7",
"C. c #77C3EA",
"Z. c #6DC4F2",
"A. c #77CAF5",
"S. c #73D2FA",
"D. c #8CC1DD",
"F. c #81C5EA",
"G. c #81C6EA",
"H. c #80CBEC",
"J. c #8FD0F0",
"K. c #84D2F8",
"L. c #95D4F3",
"P. c #99D3F1",
"I. c #91D9FD",
"U. c #9ADBF8",
"Y. c #A3DEF5",
"T. c #9DE0FF",
"R. c #A0E4FF",
"E. c #BAEBFE",
"W. c #AFF2FF",
"Q. c #F1EAE4",
/* pixels */
"            h.y.w.O.T D @.i.z.f.",
"            j.* = - E Q D.P.E.c.",
"            d.X e.W.T.R.U.L.Y.p.",
"            0.@ W I.G.G.G.G.J.t.",
"        ,   9.# R K.V.V.B.B.H.r.",
"        u y 5.& F A.m.m.n.M.C.q.",
"a k j l p x Y . S Z.k.k.v.v.g.+.",
"z s d f i 4 h ; A x.a.s.i.2.4.o.",
"g 2 e 0 e e 4 u P S.3.:.-.;.1.L ",
"9 6 5 6 0 2 3 $ B Q.Z *.&.&.,.K ",
"        > < N % m >.' $.$.X.=.J ",
"        :   U + n 8.' ' ' ' | H ",
"            I o v 7._ _ ' _  .G ",
"            C o c 6.! _ ^ ^ { V ",
"                b ..^ ^ ^ ^ {   ",
"                M <.            "
};


static const char *ico_zoom[] = {
/* columns rows colors chars-per-pixel */
"16 16 123 2 ",
"   c None",
".  c #73391A",
"X  c #1D1C4B",
"o  c #35335F",
"O  c #353561",
"+  c #3C3B67",
"@  c #504C7D",
"#  c #4D537B",
"$  c #55567C",
"%  c #863700",
"&  c #954604",
"*  c #804B1F",
"=  c #A55001",
"-  c #A65407",
";  c #A35309",
":  c #B35C01",
">  c #B2620D",
",  c #C26500",
"<  c #CE7C1C",
"1  c #D98001",
"2  c #EC8E00",
"3  c #F49A00",
"4  c #E49417",
"5  c #F3A000",
"6  c #E69C27",
"7  c #E89E35",
"8  c #F5A72B",
"9  c #FFC016",
"0  c #E7AA4C",
"q  c #F8C468",
"w  c #FFD46B",
"e  c #EFC477",
"r  c #4D5890",
"t  c #45599F",
"y  c #656588",
"u  c #66658B",
"i  c #6D6F8E",
"p  c #757895",
"a  c #777C99",
"s  c #6973A0",
"d  c #7F7FA2",
"f  c #757FAC",
"g  c #8E7B81",
"h  c #80718E",
"j  c #7986AF",
"k  c #7D8EBB",
"l  c #8988AA",
"z  c #8595BE",
"x  c #8C99BA",
"c  c #8D9ABE",
"v  c #9396B2",
"b  c #9099B7",
"n  c #929BBC",
"m  c #FEE3A4",
"M  c #FFEEB5",
"N  c #FFF5BD",
"B  c #919BC0",
"V  c #86AADC",
"C  c #87B0DF",
"Z  c #9EBBD6",
"A  c #99BDE2",
"S  c #93BFEA",
"D  c #94BEE8",
"F  c #9EC6E9",
"G  c #A5C7E6",
"H  c #A8CAE5",
"J  c #A9C9E7",
"K  c #ACCEE6",
"L  c #A2C8EC",
"P  c #A3CBEF",
"I  c #A5CAED",
"U  c #B0D4ED",
"Y  c #B9D8EC",
"T  c #BAD9ED",
"R  c #BFDBEF",
"E  c #BCDCEF",
"W  c #BEDCEF",
"Q  c #ABD1F0",
"!  c #B8DAF3",
"~  c #BCDEF2",
"^  c #BADEF6",
"/  c #CBD3DF",
"(  c #C0DFEF",
")  c #C1DFF0",
"_  c #C0DFF1",
"`  c #C5E1F0",
"'  c #C4E3F2",
"]  c #C6E3F2",
"[  c #C7E4F4",
"{  c #C8EAF7",
"}  c #CCEBF5",
"|  c #C4ECFD",
" . c #CCEBF9",
".. c #CFEDF8",
"X. c #D5EEF9",
"o. c #CFF1FF",
"O. c #D7F0F7",
"+. c #D7F1FA",
"@. c #DAF2F9",
"#. c #DCF1FA",
"$. c #DCF2FA",
"%. c #DEF3FA",
"&. c #DAF4F9",
"*. c #DDF5FA",
"=. c #DBFEFF",
"-. c #EAEFF6",
";. c #E1F2F9",
":. c #E1F3FA",
">. c #E5F7FA",
",. c #E3F5FC",
"<. c #E8F7FB",
"1. c #E7FFFF",
"2. c #E8F8FD",
"3. c #EEF8FC",
"4. c #EBFFFF",
"5. c #ECFCFD",
"6. c #F1FBFD",
"7. c #F5FBFE",
"8. c azure",
"9. c #F7FFFF",
"0. c #F9FBFE",
"q. c #FCFFFF",
"w. c white",
/* pixels */
"      l b B n v                 ",
"    c G I L D V z               ",
"  x | U H ( ] ~ D k             ",
"u {  .W [ ( 4.*.~ V l           ",
"a 4.X.+.@.] 0.8.( F f           ",
"p q.;.%.>.#.) T T I j           ",
"i q.6.6.;.,.O.) H Q s           ",
"+ -.q.7.<.@.} K ! A @           ",
"  y q.q.,.%...o.^ t             ",
"    $ / 9.1.=.Z r g 4 1         ",
"      X O # O   h 7 N e ,       ",
"                  < m M 0 :     ",
"                    > q w 6 -   ",
"                      ; 8 9 5 = ",
"                        & 2 3 * ",
"                          % .   "
};


#endif // IMAGENS_H


